#version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306

  app:
    build:
      context: .
      #dockerfile: src/Dockerfile
    depends_on:
      db: 
       condition: service_healthy
    ports:
      - 8000:8000
    environment:
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      DATA_DIR: /app/data
      LOGS_DIR: /app/logs
      BACKUPS_DIR: /app/backups
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./data:/app/data
